### ISSUE TITLE
CANNOT HAS STRING!

### ISSUE THREAD

**Issue by panicz** [leyarotheconquerer/lolcode-reference#3]
When I try to run (with 1.4) lci (commit 6762b724361a4fb471345961b4750657783aeb3b from April 13, 2017), the following line causes a failure:

CAN HAS STRING?

The interpreter reports:  unknown token at: STRING?

**Comment by leyarotheconquerer** [comment]
Unfortunately, the `STRING?` library is not yet available in the `master` branch. However, if you switch to the `future` branch, it should work as documented.

There is a proposal (https://github.com/justinmeza/lci/issues/42) to move these features from the `future` branch into `master`, but that hasn't been finished yet.

I'll go ahead and add a note to the advanced section to let people know about this in the meantime.

Thanks for pointing this out!

**Comment by leyarotheconquerer** [comment]
I've added the note in ab67786f1ba80964d09273bcd2803feef2cb5623.

Feel free to let me know if the documentation is incorrect when you use the `future` branch.
